name: CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker build . -t cyberchef
    - name: Show image info
      run: docker images
    - name: Test config
      run: docker run cyberchef nginx -t
